### ISSUE TITLE
Fails to build with gpsd 3.20

### ISSUE THREAD

**Issue by City-busz** [openstreetmap/merkaartor#204]
Arch Linux with Qt 5.14.0 and gpsd 3.20.
```
GPS/qgpsdevice.cpp: In member function ‘virtual void QGPSDDevice::onDataAvailable()’:
GPS/qgpsdevice.cpp:1055:22: error: could not convert ‘((QGPSDDevice*)this)->QGPSDDevice::gpsdata->gps_data_t::fix.gps_fix_t::time’ from ‘timespec_t’ {aka ‘timespec’} to ‘bool’
 1055 |     if (gpsdata->fix.time)
      |         ~~~~~~~~~~~~~^~~~
      |                      |
      |                      timespec_t {aka timespec}
GPS/qgpsdevice.cpp:1056:63: error: no matching function for call to ‘QDateTime::fromTime_t(timespec_t&)’
 1056 |         cur_datetime = QDateTime::fromTime_t(gpsdata->fix.time);
      |                                                               ^
```

**Comment by Krakonos** [comment]
Thanks, gpsd 3.20 changed all usage of timestamp_t to timespec_t. We need to change those lines to gpsdata->fix.time.tv_sec . I will prepare a PR.

**Comment by Krakonos** [comment]
Fix merged, tested on Arch. Thanks for the report!
