### PR TITLE
Fix build with GDAL 3.0

### LINKED ISSUE #179: Build broken with GDAL 3
Build fails hard on the import/export gdal code:
```
../../src/ImportExport/ImportExportGdal.cpp:114:54: error: assigning to 'OGRSFDriver *' from incompatible type 'GDALDriver *'
    poDriver = OGRSFDriverRegistrar::GetRegistrar()->GetDriverByName(pszDriverName);
../../src/ImportExport/ImportExportGdal.cpp:493:34: error: no member named 'Open' in 'OGRSFDriverRegistrar'
    poDS = OGRSFDriverRegistrar::Open( FileName.toUtf8().constData(), FALSE );
           ~~~~~~~~~~~~~~~~~~~~~~^
../../src/ImportExport/ImportExportGdal.cpp:520:34: error: no member named 'Open' in 'OGRSFDriverRegistrar'
    poDS = OGRSFDriverRegistrar::Open( "/vsimem/temp", FALSE );
```

### PR DESCRIPTION
**Pull request by z3ntu**
The only breaking changes that could affect this project with GDAL 3.0 from what I could find are

> * OSRImportFromEPSG() takes into account official axis order.
      Traditional GIS-friendly axis order can be restored with
      OGRSpatialReference::SetAxisMappingStrategy(OAMS_TRADITIONAL_GIS_ORDER);
>  * Same for SetWellKnownGeogCS("WGS84") / SetFromUserInput("WGS84")

I'm not sure to what extent it affects merkaartor though.

Fixes #179

### CODE REVIEW

**Comment by z3ntu** [comment]
Comments from #189 :

> It seems we need to apply the workaround mentioned, as it seems to affect getX and getY methods used during import (ImportExportGdal::parseGeometry()).

> PS this thread indicates we should look into shapefiles using WGS84 / EPSG4326 :
> https://www.mail-archive.com/search?l=gdal-dev@lists.osgeo.org&q=subject:%22%5C%5Bgdal%5C-dev%5C%5D+gdal+and+proj%22&o=newest&f=1

**Comment by pabs3** [comment]
FYI, due to the lack of a fix for this issue, Merkaartor was removed from Debian:

https://bugs.debian.org/933492

**Comment by Krakonos** [comment]
I have tested a few shapefiles using EPSG4326 and I cannot reproduce the issue stated, they all import perfectly. I guess it is safe to merge. Please fill out a bug if you hit an import problem using GDAL.
